### ISSUE TITLE
Does not work for Keil ARM MDK v.5.26.2.0

### ISSUE THREAD

**Issue by shagindl** [github0null/keil-assistant#1]
Hi.
When you open a project, it opens an empty project. [There are no files](https://gyazo.com/315e2cd403671c9357ad5edf9004a670).

**Comment by github0null** [comment]
hello.
Can you upload your **.uvprojx** and **keil-assistant.log**  file ?
These will help me find the problem. 
**keil-assistant.log** location: `./.vscode`
thanks

**Comment by shagindl** [comment]
Hello.
Attached requested files. The project is going to, but when you try to go to the place of warning or error, an error [window is displayed](https://gyazo.com/0f54ca7aa758f3b2c77dd8f54acbb289)
[keil-assistant.log](https://github.com/github0null/keil-assistant/files/4455618/keil-assistant.log)
[Project.uvprojx.zip](https://github.com/github0null/keil-assistant/files/4455623/Project.uvprojx.zip)

**Comment by github0null** [comment]
Sorry. This Keil project is a multi-target project, but the plug-in is not support for multi-target project.
