### ISSUE TITLE
打开工程出现这个情况 Cannot read property 'C51' of undefined

### ISSUE THREAD

**Issue by a0215cpl** [github0null/Keil-Assistant#1]
![image](https://user-images.githubusercontent.com/42417914/64414673-5cc49580-d0c6-11e9-8fcd-74a1e91e2157.png)

**Comment by github0null** [comment]
你好，可能是 Keil uVison 5 项目文件(.uvproj) 的问题, 如果没有xml C51节点, 会出现此问题，以xml文件格式打开 xxx.uvproj 文件,  正常的文件会有如下的C51节点
![无标题](https://user-images.githubusercontent.com/43022536/64681333-1ac69580-d4b2-11e9-8180-2a7079a53b60.png)
