### ISSUE TITLE
不显示源文件

### ISSUE THREAD

**Issue by maosuyun2009** [github0null/keil-assistant#10]
您好：
   我是用插件打开Keil的工程文件后，在vscode右侧KEIL UVISION PROJECT里面展开折叠，看不到工程里的源文件和头文件，但是点击编译按钮，可以正常编译整个工程
![image](https://user-images.githubusercontent.com/2623352/87299572-dc20c200-c53e-11ea-996b-cef0d1ac0d58.png)

**Comment by github0null** [comment]
提供一下你打开的 .uvprojx 文件

**Comment by maosuyun2009** [comment]
附件如下：
[CCM4202S_DEMO.txt](https://github.com/github0null/keil-assistant/files/4917795/CCM4202S_DEMO.txt)

**Comment by github0null** [comment]
目前不支持多目标的工程
