### ISSUE TITLE
是否按照mdk配置的优化等级进行编译

### ISSUE THREAD

**Issue by qgyhd1234** [github0null/keil-assistant#11]
点击build后，看到默认使用-j0 去编译，有些片子的flash比较紧张，默认优化等级会导致固件太大，无法下载进flash

**Comment by github0null** [comment]
-j0 是隐藏 MDK 的 GUI 窗口；
***
![image](https://user-images.githubusercontent.com/43022536/88015651-4abfda00-cb54-11ea-9683-57fc17cc153f.png)

**Comment by qgyhd1234** [comment]
谢谢，我以为和gcc的类似的
