### ISSUE TITLE
.vscode文件夹（c_cpp_properties.json）是否可以新建在打开工程的根目录下

### ISSUE THREAD

**Issue by rgw5267** [github0null/keil-assistant#13]
目前.vscode文件夹会建在.uvprojx所在目录，以后只有右键打开这个目录才能看到工程，但这个目录下没有源码就没法Ctrl+P。
多半情况源码在更上层的目录上，个人也更倾向直接右键打开工程根目录开始工作，只有这样git等插件才会工作，源码也可以都看到。
.uvprojx文件可以通过指定位置方式记录在配置文件中，但最好是相对位置
生成的c_cpp_properties.json文件includePath也最好是相对位置，因为每个人工程放的位置不一样，多人协作有些问题
个人建议.vscode新建在工程根目录下

**Comment by rgw5267** [comment]
补充一下，.uvprojx文件可以通过指定位置方式记录在配置文件中，但最好是相对位置

**Comment by github0null** [comment]
[参考一下这个做法](https://github.com/github0null/keil-assistant/issues/8)

**Comment by rgw5267** [comment]
> [参考一下这个做法](https://github.com/github0null/keil-assistant/issues/8)

这样可以解决部分问题，但是生成的 includePath是绝对路径，可以用相对路径代替吗

**Comment by github0null** [comment]
c_cpp_properties.json 里的内容都是会自动生成的，不管你的项目放在哪里都一样

**Comment by github0null** [comment]
你应该在 .gitignore 中忽略掉 c_cpp_properties.json 文件
