### ISSUE TITLE
version 1.4.0 project build fail

### ISSUE THREAD

**Issue by ironmann250** [github0null/keil-assistant#14]
![Screenshot (1)](https://user-images.githubusercontent.com/23479802/88365828-cf5f6200-cdb9-11ea-94cf-abe7b540897d.png)
using the keys F6, F9, F7 shows an error and doesn't perform anything
vs code: 1.47.2
electron: 7.3.2
chrome: 78.0.3904.130
node.js: 12.8.1
v8: 7.8.279.23-electron.0
os: windows x64 10.0.18362

**Comment by github0null** [comment]
1.40 暂时移除了快捷键
