### ISSUE TITLE
还是关于目录的问题（已经看过改workspace的方案）

### ISSUE THREAD

**Issue by ss1969** [github0null/keil-assistant#17]
还是关于目录的问题，既必须open mdk-arm目录才能正确使用
我看过改workspace的方案，但是
之前从没用过workspace，都是直接开的folder，然后Projects！插件也全部定义的根目录，.vscode也全部在跟目录
全部转化出workspace挺麻烦的，Projects插件也得调

可以加一个feature默认从选定目录的MDK-ARM子目录加载吗？

**Comment by github0null** [comment]
你只需要在 uvprojx 文件所处的目录下 右键 新建一个 *.code-workspace 文件，然后修改 folders 属性即可，不需要做其他工作；
***
![image](https://user-images.githubusercontent.com/43022536/90721858-40783380-e2ec-11ea-9806-a95e24a3c7e5.png)

**Comment by ss1969** [comment]
即使按照上面的做，Projects！插件也不能很好配合工作。
   首先我按上面说明建立这个.code-workspace文件。
   1， 如果我在Projects！插件把工程修改为\\MDK-ARM目录，打开之后，VSC会提示是否打开工作区，如果选YES，那么当前目录将会降到低一级目录，此时左下Projects！插件的当前工程提示为No Project；如果选NO，那么无法Ctrl-P等操作。
   2，  如果在Projects！插件把工程目录保持为\\MDK-ARM的上一层目录，那么Keil插件无法自动打开工程。

**Comment by ss1969** [comment]
我比较好奇，为什么不能自定义默认的uvprojx 相对于当前目录的所在目录呢？是有什么限制吗

**Comment by github0null** [comment]
1. *.code-workspace 文件所在的目录才是当前 vscode 打开的目录，这个插件只能从当前目录搜索 uvprojx 文件，并打开，你应该将 *.code-workspace 和 uvprojx 放在一起

2. 你的要求没什么问题，我一开始只是打算在 vscode 上显示出在 MDK 上看到的项目结构，然后大家都操作我提供好的视图，并没有关注工作区是否真正打开了你需要的目录，况且 MDK 显示的也是项目结构
