### ISSUE TITLE
打开vscode另存为的工作区文件无法正确加载工程

### ISSUE THREAD

**Issue by luhua2018** [github0null/keil-assistant#18]
使用vscode打开keil工程关闭后再重新打开可以正确加载上次的keil工程，但是**打开另存为的工作区文件就无法正常加载**。

![工作区文件.png](https://i.loli.net/2020/08/23/kcXDSzN3sfmnMao.png)

![直接打开.png](https://i.loli.net/2020/08/23/HRTadDNcqWlFLBS.png)

**Comment by github0null** [comment]
工作区文件所在的目录才是你当前打开的目录，这个插件只会从当前打开的目录下加载 keil 项目；
因此你必须将 *.code-workspace 文件放在 uvprojx 所在的目录下
