### ISSUE TITLE
部分keil头文件不能自动添加到c_cpp_properties.json文件中

### ISSUE THREAD

**Issue by gongzhx** [github0null/keil-assistant#19]
在x:/Users/user/AppData/Local/Arm中的头文件不能自动添加到c_cpp_properties.json文件中

**Comment by github0null** [comment]
x:/Users/user/AppData/Local/Arm 不是编译器内置的包含路径

**Comment by gongzhx** [comment]
下面这些文件就是我用keil建工程时添加的,找了一下路径都在x:/Users/user/AppData/Local/Arm里面
如果能把下面这些文件都自动添加进c_cpp_properties.json就好了，这些文件都keil里面都是只读的

`<apis>
      <api Capiversion="2.1.3" Cclass="CMSIS" Cgroup="RTOS2" exclusive="1">
        <package name="CMSIS" schemaVersion="1.3" url="http://www.keil.com/pack/" vendor="ARM" version="5.7.0"/>
        <targetInfos>
          <targetInfo name="V0.0.1"/>
        </targetInfos>
      </api>
    </apis>
    <components>
      <component Cbundle="FreeRTOS" Cclass="RTOS" Cgroup="Config" Cvariant="CMSIS RTOS2" Cvendor="ARM" Cversion="10.3.1" condition="FreeRTOS Config CMSIS RTOS2">
        <package license="License/license.txt" name="CMSIS-FreeRTOS" schemaVersion="1.4" url="http://www.keil.com/pack/" vendor="ARM" version="10.3.1"/>
        <targetInfos>
          <targetInfo name="V0.0.1"/>
        </targetInfos>
      </component>
      <component Cbundle="FreeRTOS" Cclass="RTOS" Cgroup="Core" Cvariant="Cortex-M" Cvendor="ARM" Cversion="10.3.1" condition="FreeRTOS Core CM">
        <package license="License/license.txt" name="CMSIS-FreeRTOS" schemaVersion="1.4" url="http://www.keil.com/pack/" vendor="ARM" version="10.3.1"/>
        <targetInfos>
          <targetInfo name="V0.0.1"/>
        </targetInfos>
      </component>
      <component Cbundle="FreeRTOS" Cclass="RTOS" Cgroup="Event Groups" Cvendor="ARM" Cversion="10.3.1" condition="FreeRTOS Event Groups">
        <package license="License/license.txt" name="CMSIS-FreeRTOS" schemaVersion="1.4" url="http://www.keil.com/pack/" vendor="ARM" version="10.3.1"/>
        <targetInfos>
          <targetInfo name="V0.0.1"/>
        </targetInfos>
      </component>`

**Comment by ghmoai** [comment]
这个能更新一下吗，还是蛮重要的

**Comment by github0null** [comment]
这样强加上去不够灵活，因为这个文件夹不一定存在，如果不存在的话会导致 c/c++ 插件在工作区产生警告

我建议你直接显式的在 MDK 中添加进去，再点全部保存，这样插件也能同步过来

**Comment by gongzhx** [comment]
是不是可以在设置里面建一个菜单，然后在菜单里面设置这个文件夹的路径
