### ISSUE TITLE
打开文件夹非MDK-ARM时不会自动加载工程

### ISSUE THREAD

**Issue by Ekkone** [github0null/keil-assistant#2]
使用VScode打开MDK-ARM时可以自动加载出上次打开的工程，打开上一层目录时不行。生成的.vscode默认在MDK-ARM里面，可不可以识别当前打开的目录然后放在当前目录下呢

**Comment by Ekkone** [comment]
**感谢**

**Comment by github0null** [comment]
.vscode 目录和打开的 .uvprojx 文件处于同一目录，不能随便更改位置

**Comment by Ekkone** [comment]
谢谢回答，我是觉得用VScode一般就直接打开整个工程的目录而不是MDK-ARM，所以自己的.vscode就不在那一层，希望如果可以的话可以增加这样的功能。
不过目前使用也很不错，感谢开发出这么方便的插件，加油，会持续关注您的。

**Comment by github0null** [comment]
keil 是根据 .uvprojx 来定位项目位置的，.uvprojx 所处的目录**并不是项目根目录**；
而 vscode 是根据 .code-workspace 来确定项目位置的，.code-workspace 所处的目录就是项目根目录

因此两个并不能很好的融合，不过我也提供了项目视图，帮助打开，编辑源文件

**Comment by github0null** [comment]
可以通过修改 .code-workspace 的 path 字段来达到你要的结果
这样就能打开根目录

**Comment by Ekkone** [comment]
谢谢，我试试看

**Comment by Ekkone** [comment]
用工作区的方式的确可以达到我想要的效果，谢谢！
请问编译、下载、重新编译这几个选项可以制作个命令然后用快捷键的方式实现不，这样会比较方便些

**Comment by Ekkone** [comment]
![image](https://user-images.githubusercontent.com/38444906/78204868-5d42d480-74cd-11ea-897d-b14c1245f3c5.png)
我使用**task.json**复制了编译时的命令好像也不行，请教这个用**task.json**的话应该怎么写呢？

**Comment by github0null** [comment]
快捷键会加上的，你复制到 task 里的命令没什么问题，只是 Keil 编译的输出只能输出到文件，因此你需要把那个文件的内容显示出来

**Comment by Ekkone** [comment]
好的，所以其实已经编译了，只是没有把输出打印出来对吧，需要加一个打印日志的命令就好了

**Comment by github0null** [comment]
是的
