### ISSUE TITLE
错误识别arm工程为c51工程

### ISSUE THREAD

**Issue by PurplePopo** [github0null/keil-assistant#22]
在我添加某个工程时，错误的将ARM工程识别为C51工程。
我的工程路径下有部分文件命名包含“C51”文字

**Comment by github0null** [comment]
插件靠 keil 项目文件后缀来识别项目类型， uvproj 代表 C51 工程，uvprojx 代表 ARM 工程

**Comment by ekerV5** [comment]
我的项目是ARM的，但工程文件是uvproj类型

**Comment by ekerV5** [comment]
> 插件靠 keil 项目文件后缀来识别项目类型， uvproj 代表 C51 工程，uvprojx 代表 ARM 工程

我的项目是ARM的，但工程文件是uvproj类型

**Comment by github0null** [comment]
因为 Keil 4 及以下的版本的所有项目都是 uvproj 结尾，没有区分，而 keil 5 的 ARM 项目是 uvprojx， C51 项目是 uvproj

**我的插件是根据 keil 5 制作的**，所以插件是根据 **keil 项目文件后缀** 来判断项目类型，你用 MDK 526 打开 uvproj 文件的项目，它也会提示你需要进行一些兼容的操作

你可以直接更改后缀为 uvprojx 试试
