### ISSUE TITLE
打开工程后只能显示工程文件所在目录

### ISSUE THREAD

**Issue by katcoo** [github0null/keil-assistant#32]
工程文件在路径/prj下，打开工程文件后，只能显示prj文件夹内的文件，请教无法显示prj同等级路径下的代码文件夹是啥原因？

**Comment by ekerV5** [comment]
这个问题能解决吗？我的也是，打开工程后只显示工程文件所在目录，上级、上上级目录都没有加载进来

**Comment by github0null** [comment]
1. 这个插件只能显示 keil 项目管理器所显示的，点开 UVISION PROJECTS 栏就能看到
2. 不要看 vscode 文件资源管理器，因为它显示的是文件夹，当然只能看到 uvprojx 所在的目录
===============================================================
3. 后面可能会再加一个 **选择项目根目录** 的功能，这样就能够打你想要打开的文件夹

**Comment by github0null** [comment]
对于这个问题，又有了新的解决方法：
1. 为uvprojx创建符号链接，这样你就可以在任何地方打开
2. 使用最新版的 eide 导入 keil 项目，在导入的时候，根据提示重新选择项目根目录
