### ISSUE TITLE
Erase Failed!Error: Flash Download failed  -  "Cortex-M3"

### ISSUE THREAD

**Issue by tiny138** [github0null/keil-assistant#38]
我在keil里面可以building和load，但是在VScode里面出现可以bulit，但是无法load的情况，报错信息：

Load "..\\OBJ\\LED.axf"
Erase Failed!Error: Flash Download failed  -  "Cortex-M3"
Flash Load finished at 20:08:14

这个是什么原因捏

**Comment by github0null** [comment]
在 keil 上点击保存所有，将配置保存到 uvprojx 后，再使用 keil-assistant 的下载功能试试。

因为 keil 上的下载配置改了，但没有保存到uvprojx 文件，所以插件用的还是旧的配置。

**Comment by tiny138** [comment]
可以了，多谢
