### ISSUE TITLE
希望打开vscode时自动打开当前目录下所以子目录的keil工程文件

### ISSUE THREAD

**Issue by Atom2004** [github0null/keil-assistant#39]
在`\A\MDK\`目录下，有一个keil工程`\A\MDK\Project.uvprojx`
通过vscode打开\A目录时，希望keil-assistant能自动找到并打开`\A\MDK\Project.uvprojx`工程文件。
不需要手动点击 KEIL UVISION PROJECT 上的加号在选择对应的`*.uvprojx`文件。

而目前发现用vscode打开`\A\MDK\`目录后，KEIL UVISION PROJECT 中可以自动加载`Project.uvprojx`工程文件

![image](https://user-images.githubusercontent.com/22042246/106112433-36563d00-6188-11eb-90d5-b6edd4999739.png)

**Comment by github0null** [comment]
- 递归的搜索目录不是一个好方法，因为有很多项目都会放在一个共同的根目录下，比如某些芯片的示例工程，可能有几百个
- 有个替代的方法，我还没有实现，在 #32 里

**Comment by Atom2004** [comment]
> * 递归的搜索目录不是一个好方法，因为有很多项目都会放在一个共同的根目录下，比如某些芯片的示例工程，可能有几百个
> * 有个替代的方法，我还没有实现，在 #32 里

非常期待
