### ISSUE TITLE
你好，请问这个和EIDE 有区别吗？

### ISSUE THREAD

**Issue by heartacker** [github0null/keil-assistant#4]
我是同时需要C51 和ARM cortex，请问是需要安装这两个吗？还是安装EIDE或者keil-assistant 的其中一个就好了

**Comment by github0null** [comment]
两个选一个就行
*** 
如果你只想在 vscode 上编辑，其他功能都在 keil 上进行，选择 keil-assistant
如果你想全套都在 vscode 上进行，选择 eide
