### ISSUE TITLE
如果方便的话,问一下,我不能编译是什么问题,您清楚吗,当点击插件的编译时不能编译

### ISSUE THREAD

**Issue by huyunlei** [github0null/keil-assistant#5]
![image](https://user-images.githubusercontent.com/57059809/83346162-a5a33500-a34c-11ea-937d-d874e5b7e0b8.png)
 
搜索半天也没解决,您如果知道的话,麻烦告诉我

**Comment by huyunlei** [comment]
第一次用github感觉这个太流批了,甚至可以和外国人交流

**Comment by github0null** [comment]
请检查 UV4.exe 的路径是否正确
