### ISSUE TITLE
stm32CubeMx生成的MDK工程,VSCode中自动配置的c_cpp_properties.json中的includePath有问题.

### ISSUE THREAD

**Issue by yanllllk** [github0null/keil-assistant#7]
stm32CubeMx生成的MDK工程,VSCode中自动配置的c_cpp_properties.json中的includePath有问题.
如果是MDK直接生成的工程,include没啥问题.
如果是stm32CubeMx生成的MDK工程.includePath里会成这样:
![微信图片_20200616102546](https://user-images.githubusercontent.com/31483702/84724868-c9f14980-afbb-11ea-8034-d4e2986f08e7.png)
上图中,工程路径MDK-ARM\\后,会多5个空格.导至C++插件,无法认识.每次只能手动删除5个空格才能正常.

**Comment by yanllllk** [comment]
另外代码里,缺少lib/node-utility

**Comment by yanllllk** [comment]
extension.ts 文件中, reload 函数里.
        incList.forEach((path) => {
            if (path.trim() !== '') {
                this.includes.add(this.toAbsolutePath(path));
            }
        });
改成
        incList.forEach((path) => {
            if (path.trim() !== '') {
                this.includes.add(this.toAbsolutePath(path.trim()));
            }
        });

就可以解决这个问题

**Comment by github0null** [comment]
你好，已经修复；
但是出现这种问题的原因是 keil 项目配置的 include 路径中有空格

**Comment by yanllllk** [comment]
是的...cubeMx生成的工程里,有空格.
