### ISSUE TITLE
项目文件（.uvprojx）不在根目录下的打开问题

### ISSUE THREAD

**Issue by tjye** [github0null/keil-assistant#8]
你好，我在VS Code打开我的工作文件夹，但是由于项目文件（.uvprojx）是在当前目录的子文件夹下，所以没法自动识别，需要手动打开，每次重新打开VS Code都需如此，是否可以增加自动检索当前工作空间下（包含子文件夹）的项目文件的功能，谢谢！

**Comment by github0null** [comment]
必须打开 uvprojx 所在的目录，才能加载项目
你可以向 .code-workspace 工作区文件的 folders 属性添加 路径 来显示出项目根目录；
就像下图所示；
***
![image](https://user-images.githubusercontent.com/43022536/85815464-0e8a9b00-b79b-11ea-87b8-478fc040fefc.png)

**Comment by ZemingLiu** [comment]
> 必须打开 uvprojx 所在的目录，才能加载项目
> 你可以向 .code-workspace 工作区文件的 folders 属性添加 路径 来显示出项目根目录；
> 就像下图所示；
> 
> ![image](https://user-images.githubusercontent.com/43022536/85815464-0e8a9b00-b79b-11ea-87b8-478fc040fefc.png)

STM32CubeMX生成的工程，导入后工作正常。但因为.vscode不在项目根目录，导致全局搜索和Ctrl+P失效
在工作区添加folders属性后，全局搜索和Ctrl+P功能正常
![image](https://user-images.githubusercontent.com/2747603/89366607-c485c500-d709-11ea-8016-95ffc33d67bb.png)
![image](https://user-images.githubusercontent.com/2747603/89366809-2ba37980-d70a-11ea-9b44-c7807b647466.png)

但似乎会引起索引误报，如下图，请问是否有解决方案？谢谢
![image](https://user-images.githubusercontent.com/2747603/89366290-327dbc80-d709-11ea-990c-b10f3f886ab6.png)
