### ISSUE TITLE
使用ARM Compiler6和gnu11的问题

### ISSUE THREAD

**Issue by YiFnp** [github0null/keil-assistant#9]
您好：
在keil内选择使用ARM Compiler6和gnu11，
![2](https://user-images.githubusercontent.com/21213212/87265907-7f99b480-c4f6-11ea-8a45-be5a85f19a06.png)

![1](https://user-images.githubusercontent.com/21213212/87265897-7ad50080-c4f6-11ea-8b83-6e055c2c3102.png)

自动生成的vs项目c_cpp_properties.json还是标准c："__CC_ARM"。
includePath的include文件目录“Keil_v5\\ARM\\ARMCC\\include”
![3](https://user-images.githubusercontent.com/21213212/87265821-537e3380-c4f6-11ea-8eab-ea6c3a95fd50.png)
![5](https://user-images.githubusercontent.com/21213212/87265822-537e3380-c4f6-11ea-8e05-f18233131df4.png)
![4](https://user-images.githubusercontent.com/21213212/87265840-5ed15f00-c4f6-11ea-9093-b03acd51f9ef.png)
但是编译没问题

**Comment by github0null** [comment]
这个只是给 c/c++ 插件用的，和编译没关系
**ArmClang 的定义以后会加上**

**Comment by YiFnp** [comment]
> 这个只是给 c/c++ 插件用的，和编译没关系
> **ArmClang 的定义以后会加上**

明白了，多谢
